name:  Docker Image Ci-Cd Pipeline
on:
  push:
     branches: [ main ]
  pull_request:
     branches: [ main ]
  workflow_dispatch:
jobs:
  Setting-Up-The-Node-Env:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]   
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
  Installing-App-Dependencies:
    runs-on: ubuntu-latest
    needs: Setting-Up-The-Node-Env
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm ci     
      - name: build
        run: |
          npm run build
  Jfrog-Login:
    runs-on: ubuntu-latest
    needs: Installing-App-Dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Login to JFrog 
        uses: docker/login-action@v1
        with:
          registry: underconstruction.jfrog.io
          username: ${{ secrets.JFROG_USERNAME}}
          password: ${{ secrets.JFROG_PASSWORD}}

