name: Docker Image Ci-Cd Pipeline
on:
  push:
     branches: [ main ]
  pull_request:
     branches: [ main ]
  workflow_dispatch:

jobs:
  Setting-Up-The-Node-Env:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 14.x

  Installing-App-Dependencies:
    runs-on: ubuntu-latest
    needs: Setting-Up-The-Node-Env
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm ci     
      - name: build
        run: |
          npm run build

  Scanning:
    runs-on: ubuntu-latest
    needs: Installing-App-Dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}
          exit-code: '0'
          ignore-unfixed: true 
          format: 'sarif'
          output: 'trivy-results.sarif'
          vuln-type: 'os,library'
          severity: 'LOW,MEDIUM'

  Docker-Build:
    runs-on: ubuntu-latest
    needs: Scanning
    steps:
      - name: Jfrog login 
        uses: docker/login-action@v1
        with:
          registry: underconstruction.jfrog.io
          username: ${{ secrets.JFROG_USERNAME}}
          password: ${{ secrets.JFROG_PASSWORD}}
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: underconstruction.jfrog.io/docker-dev/cell-game:version-${{ github.run_id }}-${{ github.run_attempt }}
          outputs: type=oci,dest=/tmp/image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-build
          path: /tmp/image.tar
      - uses: actions/upload-artifact@v2
        with:
          name: underconstruction.jfrog.io/docker-dev/cell-game:version-${{ github.run_id }}-${{ github.run_attempt }}
          path: underconstruction.jfrog.io/docker-dev/cell-game:version-${{ github.run_id }}-${{ github.run_attempt }}
          if-no-files-found: error
  
  Docker-validate:
    runs-on: ubuntu-latest
    needs: Docker-Build
    steps:
      - name: Jfrog login 
        uses: docker/login-action@v1
        with:
          registry: underconstruction.jfrog.io
          username: ${{ secrets.JFROG_USERNAME}}
          password: ${{ secrets.JFROG_PASSWORD}}

      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: underconstruction.jfrog.io/docker-dev/cell-game:version-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'underconstruction.jfrog.io/docker-dev/cell-game:version-${{ github.run_id }}-${{ github.run_attempt }}'
          exit-code: '0'
          ignore-unfixed: true 
          format: 'sarif'
          output: 'trivy-results.sarif'
          vuln-type: 'os,library'
          severity: 'LOW,MEDIUM'

  Push-To-Artifactory:
    runs-on: ubuntu-latest
    needs: Docker-validate
    steps:
      - name: Jfrog login 
        uses: docker/login-action@v1
        with:
          registry: underconstruction.jfrog.io
          username: ${{ secrets.JFROG_USERNAME}}
          password: ${{ secrets.JFROG_PASSWORD}}
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: underconstruction.jfrog.io/docker-dev/cell-game:version-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Pushing the Image into our Artifactory
        run: docker push underconstruction.jfrog.io/docker-dev/cell-game:version-${{ github.run_id }}-${{ github.run_attempt }}
