name: Test Docker
on:
  push:
     branches: [ main ]
  pull_request:
     branches: [ main ]
  workflow_dispatch:
  
env:
  VERSION_LEVEL: 0.0.0

jobs:
  Docker-Build-and-Push-to-Artifactory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      
      - name: Increment Step
        id: increment-version
        uses: ./actions
        with:
          version-level: '-p'
          
      - name: Set env variable
        run: |
          touch .env
          echo "VERSION_LEVEL=${{ steps.increment-version.outputs.version}}" >> .env
          cat .env
        
      - name: Print env variable
        run: echo 'VERSION_LEVEL is' $VERSION_LEVEL
        # prints 'TEST_RESULT is failure'
   
  Create-Release:
    runs-on: ubuntu-latest
    needs: Docker-Build-and-Push-to-Artifactory
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: $VERSION_LEVEL
          release_name: Release $VERSION_LEVEL
          draft: false
          prerelease: false
#       - name: Jfrog Login
#         uses: docker/login-action@v1
#         with:
#           registry: underconstruction.jfrog.io
#           username: ${{ secrets.JFROG_USERNAME}}
#           password: ${{ secrets.JFROG_PASSWORD}}

#       - name: Building the Docker Image
#         run: docker build --tag underconstruction.jfrog.io/docker-dev/cell-game:version-${{ steps.increment-version.outputs.version }} .
          #run: docker build --tag underconstruction.jfrog.io/docker-dev/cell-game:version-${{ github.run_id }}-${{ github.run_attempt }} .
